import {
  generateImage as generateImageWithImageModel,
  generateText,
  tool,
  type FilePart,
  type ImagePart,
  type TextPart,
} from "ai";
import { z } from "zod";
import {
  defineTool,
  type ToolRuntimeContext,
} from "@toolkit/lib/runtime";

type ImageMode = "edit" | "generate";

async function filePartToBuffer(file: FilePart): Promise<Buffer> {
  if (file.data instanceof URL) {
    const response = await fetch(file.data);
    const arrayBuffer = await response.arrayBuffer();
    return Buffer.from(arrayBuffer);
  }
  if (typeof file.data === "string") {
    return Buffer.from(file.data, "base64");
  }
  if (file.data instanceof ArrayBuffer) {
    return Buffer.from(new Uint8Array(file.data));
  }
  return Buffer.from(file.data);
}

async function collectEditImageBuffers(files: FilePart[]): Promise<Buffer[]> {
  return Promise.all(files.map((file) => filePartToBuffer(file)));
}

function mediaExtension(mediaType: string): string {
  return mediaType.split("/")[1]?.split(";")[0] || "png";
}

export const generateImage = defineTool({
  id: "generate-image",
  needs: [
    "files.attachments",
    "files.previous",
    "media.write",
    "models.image",
  ],
  createTool: (ctx: ToolRuntimeContext) =>
    tool({
      description: `Generate an image from a user-provided prompt.

The assistant may make small, neutral adjustments to improve clarity, composition, or technical quality, while strictly preserving the user's original intent, meaning, and message.

The assistant must not add new subjects, claims, branding, or alter the tone or intent of the prompt.
`,
      inputSchema: z.object({
        prompt: z
          .string()
          .describe(
            "The user's image prompt. The original intent, message, and meaning must remain unchanged. No new ideas, claims, or content may be introduced."
          ),
      }),
      execute: async ({ prompt }, { abortSignal }) => {
        const [attachments, previousImages] = await Promise.all([
          ctx.files.attachments({ mediaTypes: ["image/"] }),
          ctx.files.previous({ kind: "image", limit: 1 }),
        ]);
        const imageInputs = [...previousImages, ...attachments];
        const mode: ImageMode = imageInputs.length > 0 ? "edit" : "generate";
        const imageGenerationModel = await ctx.models.imageGeneration({
          purpose: "generate-image",
        });

        if (imageGenerationModel.type === "language") {
          const userContent: Array<ImagePart | TextPart> = [];

          if (mode === "edit") {
            for (const image of imageInputs) {
              userContent.push({
                image: image.data,
                mediaType: image.mediaType,
                type: "image",
              });
            }
          }

          userContent.push({
            type: "text",
            text:
              mode === "edit"
                ? `Based on the provided image(s), ${prompt}`
                : `Generate an image: ${prompt}`,
          });

          const isGoogleModel =
            imageGenerationModel.modelId.startsWith("google/") ||
            imageGenerationModel.modelId.includes("gemini");
          const isOpenAIModel = imageGenerationModel.modelId.startsWith(
            "openai/"
          );

          const result = await generateText({
            abortSignal,
            messages: [{ role: "user", content: userContent }],
            model: imageGenerationModel.model,
            providerOptions: {
              ...(isGoogleModel && {
                google: {
                  responseModalities: ["TEXT", "IMAGE"],
                },
              }),
              ...(isOpenAIModel && {
                openai: {
                  modalities: ["text", "image"],
                },
              }),
            },
          });
          if (result.usage) {
            ctx.cost.addLLMCost(
              imageGenerationModel.modelId,
              result.usage,
              "generateImage-multimodal"
            );
          }

          const imageFile = result.files?.find((file) =>
            file.mediaType.startsWith("image/")
          );
          if (!imageFile) {
            throw new Error("No image generated by multimodal model");
          }

          const stored = await ctx.media.write({
            bytes: imageFile.uint8Array,
            filename: `generated-image-${Date.now()}.${mediaExtension(imageFile.mediaType)}`,
            mediaType: imageFile.mediaType,
          });

          return {
            imageUrl: stored.url,
            prompt,
          };
        }

        const imageBuffers =
          mode === "edit" ? await collectEditImageBuffers(imageInputs) : [];
        const promptInput =
          mode === "edit" ? { text: prompt, images: imageBuffers } : prompt;

        const result = await generateImageWithImageModel({
          abortSignal,
          model: imageGenerationModel.model,
          n: 1,
          prompt: promptInput,
          providerOptions: {
            telemetry: { isEnabled: true },
          },
        });

        const image = result.images[0];
        if (!image) {
          throw new Error("No image generated");
        }

        const stored = await ctx.media.write({
          bytes: image.uint8Array,
          filename: `generated-image-${Date.now()}.${mediaExtension(image.mediaType)}`,
          mediaType: image.mediaType,
        });
        if (result.usage) {
          ctx.cost.addLLMCost(
            imageGenerationModel.modelId,
            {
              inputTokens: result.usage.inputTokens,
              outputTokens: result.usage.outputTokens,
            },
            "generateImage-traditional"
          );
        }

        return {
          imageUrl: stored.url,
          prompt,
        };
      },
      toModelOutput: ({ output }) => ({
        type: "json",
        value: {
          imageUrl: output.imageUrl,
          prompt: output.prompt,
        },
      }),
    }),
} as const);
