import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	type EnvVar,
	getProvider,
	PROVIDER_NAMES,
	type ProviderSlug,
} from "files-sdk/providers";

export type StorageSelection = {
	provider: ProviderSlug;
	options: Record<string, unknown>;
};

const STORAGE_ENV_START = "# <chatjs-storage-provider>";
const STORAGE_ENV_END = "# </chatjs-storage-provider>";
const UNSUPPORTED_SCAFFOLD_PROVIDERS = new Set<ProviderSlug>([
	"bun-s3",
	"convex",
	"memory",
]);

export const INSTALLABLE_STORAGE_PROVIDERS = PROVIDER_NAMES.filter(
	(provider) => !UNSUPPORTED_SCAFFOLD_PROVIDERS.has(provider),
);

export function parseStorageOptions(value: string): Record<string, unknown> {
	let parsed: unknown;
	try {
		parsed = JSON.parse(value);
	} catch {
		throw new Error("Storage config must be a valid JSON object.");
	}
	if (!(parsed && typeof parsed === "object" && !Array.isArray(parsed))) {
		throw new Error("Storage config must be a JSON object.");
	}
	return parsed as Record<string, unknown>;
}

export function resolveStorageProvider(value: string): ProviderSlug {
	if (!INSTALLABLE_STORAGE_PROVIDERS.includes(value as ProviderSlug)) {
		throw new Error(`Unknown Files SDK provider: ${value}`);
	}
	return value as ProviderSlug;
}

export function storageEnvRequirements(
	provider: ProviderSlug,
	options: Record<string, unknown> = {},
): Array<{
	description: string;
	options: string[][];
}> {
	const metadata = getProvider(provider);
	if (!metadata) {
		return [];
	}

	const requirements: Array<{ description: string; options: string[][] }> = [];
	const required = metadata.env.required?.filter(
		(variable) => {
			const optionName = /or pass `([^`]+)`/.exec(variable.description)?.[1];
			return (
				variable.readBy === "files-sdk" &&
				!(optionName && options[optionName] !== undefined)
			);
		},
	);
	if (required?.length) {
		requirements.push({
			description: `${metadata.name} configuration`,
			options: [required.map(({ key }) => key)],
		});
	}
	const modes = metadata.env.credentialModes
		?.map((mode) =>
			mode.vars
				.filter((variable) => variable.readBy === "files-sdk")
				.map(({ key }) => key),
		);
	if (modes?.length && modes.every((keys) => keys.length > 0)) {
		requirements.push({
			description: `${metadata.name} credentials`,
			options: modes,
		});
	}
	return requirements;
}

function findFilesSdkPackageJson(): string {
	let current = dirname(fileURLToPath(import.meta.resolve("files-sdk")));
	while (dirname(current) !== current) {
		const candidate = join(current, "package.json");
		if (existsSync(candidate)) {
			return candidate;
		}
		current = dirname(current);
	}
	throw new Error("Could not locate the files-sdk package manifest.");
}

function renderEnvVariable(variable: EnvVar, optional = false): string[] {
	return optional
		? [`# ${variable.key}= # ${variable.description}`]
		: [`# ${variable.description}`, `${variable.key}=`];
}

export async function configureStorageProvider(
	destination: string,
	selection: StorageSelection,
): Promise<void> {
	const metadata = getProvider(selection.provider);
	if (!metadata) {
		throw new Error(`Unknown Files SDK provider: ${selection.provider}`);
	}

	const sdkPackage = JSON.parse(
		await readFile(findFilesSdkPackageJson(), "utf8"),
	) as { peerDependencies?: Record<string, string> };
	const packagePath = join(destination, "package.json");
	const packageJson = JSON.parse(await readFile(packagePath, "utf8")) as {
		dependencies?: Record<string, string>;
	};
	const existing = packageJson.dependencies ?? {};
	const allProviderPeers = new Set(
		PROVIDER_NAMES.flatMap((slug) => getProvider(slug)?.peerDeps ?? []),
	);
	const dependencies = Object.fromEntries(
		Object.entries(existing).filter(([name]) => !allProviderPeers.has(name)),
	);
	for (const peer of metadata.peerDeps) {
		const version = sdkPackage.peerDependencies?.[peer];
		if (!version) {
			throw new Error(`No files-sdk peer version found for ${peer}`);
		}
		dependencies[peer] = existing[peer] ?? version;
	}
	packageJson.dependencies = dependencies;
	await writeFile(packagePath, `${JSON.stringify(packageJson, null, 2)}\n`);

	const providerSource = `// Generated by ChatJS. Re-run the installer to switch providers.
// biome-ignore lint/performance/noNamespaceImport: provider factories have provider-specific names
import * as storageProviderModule from "files-sdk/${selection.provider}";

export const storageProvider = {
  module: storageProviderModule as Record<string, unknown>,
  options: ${JSON.stringify(selection.options, null, 2)},
  slug: "${selection.provider}",
} as const;
`;
	await writeFile(
		join(destination, "lib", "storage-provider.ts"),
		providerSource,
	);

	const envPath = join(destination, ".env.example");
	const env = await readFile(envPath, "utf8");
	const start = env.indexOf(STORAGE_ENV_START);
	const end = env.indexOf(STORAGE_ENV_END);
	if (start === -1 || end <= start) {
		return;
	}

	const lines = [
		STORAGE_ENV_START,
		`# ${metadata.name} — ${metadata.description}`,
		...(metadata.env.required ?? []).flatMap((variable) =>
			renderEnvVariable(variable),
		),
		...(metadata.env.credentialModes ?? []).flatMap((mode) => [
			`# Credential option: ${mode.label}`,
			...mode.vars.flatMap((variable) => renderEnvVariable(variable)),
		]),
		...(metadata.env.optional ?? []).flatMap((variable) =>
			renderEnvVariable(variable, true),
		),
		...(metadata.env.notes ? [`# Note: ${metadata.env.notes}`] : []),
		STORAGE_ENV_END,
	];
	const updated = `${env.slice(0, start)}${lines.join("\n")}${env.slice(end + STORAGE_ENV_END.length)}`;
	await writeFile(envPath, updated);
}
