import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	type EnvVar,
	getProvider,
	PROVIDER_NAMES,
	type ProviderSlug,
} from "files-sdk/providers";
import { getStorageEnvironmentRequirements } from "../../../../apps/chat/lib/storage-provider-metadata";

export type StorageSelection = {
	provider: ProviderSlug;
	options: Record<string, unknown>;
};

const STORAGE_ENV_START = "# <chatjs-storage-provider>";
const STORAGE_ENV_END = "# </chatjs-storage-provider>";
const UNSUPPORTED_SCAFFOLD_PROVIDERS = new Set<ProviderSlug>([
	"bun-s3",
	"convex",
	"memory",
]);

export const INSTALLABLE_STORAGE_PROVIDERS = PROVIDER_NAMES.filter(
	(provider) => !UNSUPPORTED_SCAFFOLD_PROVIDERS.has(provider),
);

export function parseStorageOptions(value: string): Record<string, unknown> {
	let parsed: unknown;
	try {
		parsed = JSON.parse(value);
	} catch {
		throw new Error("Storage config must be a valid JSON object.");
	}
	if (!(parsed && typeof parsed === "object" && !Array.isArray(parsed))) {
		throw new Error("Storage config must be a JSON object.");
	}
	return parsed as Record<string, unknown>;
}

export function resolveStorageProvider(value: string): ProviderSlug {
	if (!INSTALLABLE_STORAGE_PROVIDERS.includes(value as ProviderSlug)) {
		throw new Error(`Unknown Files SDK provider: ${value}`);
	}
	return value as ProviderSlug;
}

export function storageEnvRequirements(
	provider: ProviderSlug,
	options: Record<string, unknown> = {},
): Array<{
	description: string;
	options: string[][];
}> {
	return getStorageEnvironmentRequirements(provider, options).map(
		(requirement) => ({
			description: requirement.description,
			options: requirement.options.map((option) =>
				option.map(({ key }) => key),
			),
		}),
	);
}

function findFilesSdkPackageJson(): string {
	let current = dirname(fileURLToPath(import.meta.resolve("files-sdk")));
	while (dirname(current) !== current) {
		const candidate = join(current, "package.json");
		if (existsSync(candidate)) {
			return candidate;
		}
		current = dirname(current);
	}
	throw new Error("Could not locate the files-sdk package manifest.");
}

function renderEnvVariable(variable: EnvVar, optional = false): string[] {
	return optional
		? [`# ${variable.key}= # ${variable.description}`]
		: [`# ${variable.description}`, `${variable.key}=`];
}

export function getProviderFactoryName(provider: ProviderSlug): string {
	return provider.replace(/-([a-z0-9])/g, (_, character: string) =>
		character.toUpperCase(),
	);
}

async function getConfiguredProvider(
	destination: string,
): Promise<ProviderSlug | null> {
	const providerPath = join(destination, "lib", "storage-provider.ts");
	if (!existsSync(providerPath)) {
		return null;
	}
	const source = await readFile(providerPath, "utf8");
	const slug = /from "files-sdk\/([^"/]+)"/.exec(source)?.[1];
	return slug && PROVIDER_NAMES.includes(slug as ProviderSlug)
		? (slug as ProviderSlug)
		: null;
}

export async function configureStorageProvider(
	destination: string,
	selection: StorageSelection,
): Promise<void> {
	const metadata = getProvider(selection.provider);
	if (!metadata) {
		throw new Error(`Unknown Files SDK provider: ${selection.provider}`);
	}

	const sdkPackage = JSON.parse(
		await readFile(findFilesSdkPackageJson(), "utf8"),
	) as { peerDependencies?: Record<string, string> };
	const packagePath = join(destination, "package.json");
	const packageJson = JSON.parse(await readFile(packagePath, "utf8")) as {
		dependencies?: Record<string, string>;
	};
	const existing = packageJson.dependencies ?? {};
	const previousProvider = await getConfiguredProvider(destination);
	const previousProviderPeers = new Set(
		previousProvider ? (getProvider(previousProvider)?.peerDeps ?? []) : [],
	);
	const dependencies = Object.fromEntries(
		Object.entries(existing).filter(
			([name]) => !previousProviderPeers.has(name),
		),
	);
	for (const peer of metadata.peerDeps) {
		const version = sdkPackage.peerDependencies?.[peer];
		if (!version) {
			throw new Error(`No files-sdk peer version found for ${peer}`);
		}
		dependencies[peer] = existing[peer] ?? version;
	}
	packageJson.dependencies = dependencies;
	await writeFile(packagePath, `${JSON.stringify(packageJson, null, 2)}\n`);

	const factoryName = getProviderFactoryName(selection.provider);
	const providerSource = `// Generated by ChatJS. Re-run the installer to switch providers.
import { ${factoryName} } from "files-sdk/${selection.provider}";

const options = ${JSON.stringify(selection.options, null, 2)} satisfies Parameters<typeof ${factoryName}>[0];

export const storageProvider = {
  createAdapter: () => ${factoryName}(options),
  options,
  slug: "${selection.provider}",
} as const;
`;
	await writeFile(
		join(destination, "lib", "storage-provider.ts"),
		providerSource,
	);

	const envPath = join(destination, ".env.example");
	const env = await readFile(envPath, "utf8");
	const start = env.indexOf(STORAGE_ENV_START);
	const end = env.indexOf(STORAGE_ENV_END);
	if (start === -1 || end <= start) {
		return;
	}

	const lines = [
		STORAGE_ENV_START,
		`# ${metadata.name} — ${metadata.description}`,
		...(metadata.env.required ?? []).flatMap((variable) =>
			renderEnvVariable(variable),
		),
		...(metadata.env.credentialModes ?? []).flatMap((mode) => [
			`# Credential option: ${mode.label}`,
			...mode.vars.flatMap((variable) => renderEnvVariable(variable)),
		]),
		...(metadata.env.optional ?? []).flatMap((variable) =>
			renderEnvVariable(variable, true),
		),
		...(metadata.env.notes ? [`# Note: ${metadata.env.notes}`] : []),
		STORAGE_ENV_END,
	];
	const updated = `${env.slice(0, start)}${lines.join("\n")}${env.slice(end + STORAGE_ENV_END.length)}`;
	await writeFile(envPath, updated);
}
