import assert from "node:assert/strict";
import { describe, it } from "vitest";
import { getFileImageProps, isFileStorageKey } from "./file-url";

describe("isFileStorageKey", () => {
  it("recognizes only keys generated by the Files SDK integration", () => {
    assert.equal(isFileStorageKey("l_u0a2bkphKLFKsBI4q5Tue9.png"), true);
    assert.equal(isFileStorageKey("legacy-upload-name.png"), false);
    assert.equal(isFileStorageKey("folder/legacy-upload.png"), false);
  });
});

describe("getFileImageProps", () => {
  it("makes managed worktree files same-origin for Next Image", () => {
    assert.deepEqual(
      getFileImageProps(
        "http://localhost:3030/api/files/content?key=l_u0a2bkphKLFKsBI4q5Tue9.png"
      ),
      {
        src: "/api/files/content?key=l_u0a2bkphKLFKsBI4q5Tue9.png",
        unoptimized: true,
      }
    );
  });

  it("leaves external images unchanged", () => {
    const url = "https://example.com/image.png";
    assert.deepEqual(getFileImageProps(url), { src: url, unoptimized: false });
  });
});
