import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import type { ForgeConfig } from "@electron-forge/shared-types";
import { MakerDeb } from "@electron-forge/maker-deb";
import { MakerDMG } from "@electron-forge/maker-dmg";
import { MakerRpm } from "@electron-forge/maker-rpm";
import { MakerSquirrel } from "@electron-forge/maker-squirrel";
import { MakerZIP } from "@electron-forge/maker-zip";

type Branding = {
  appName: string;
  appPrefix: string;
  appUrl: string;
  orgName?: string;
  orgEmail?: string;
};

const appRoot = __dirname;
const brandingPath = join(appRoot, "branding.json");
let prebuildComplete = false;

function loadBranding(): Branding {
  ensurePrebuild();

  if (!existsSync(brandingPath)) {
    throw new Error(
      `Electron packaging requires ${brandingPath}, but it was not generated by prebuild. ` +
        `Run \`bun run prebuild\` in ${appRoot} and try again.`
    );
  }

  const branding = JSON.parse(readFileSync(brandingPath, "utf8")) as Partial<Branding>;

  if (!branding.appName || !branding.appPrefix || !branding.appUrl) {
    throw new Error(
      `Electron branding file ${brandingPath} is invalid. Expected appName, appPrefix, and appUrl.`
    );
  }

  return branding as Branding;
}

function runBunScript(script: string, env: NodeJS.ProcessEnv = {}): void {
  const result = spawnSync("bun", ["run", script], {
    stdio: "inherit",
    env: { ...process.env, ...env },
  });

  if (result.status !== 0) {
    throw new Error(`bun run ${script} failed with exit code ${result.status ?? "unknown"}`);
  }
}

function ensurePrebuild(): void {
  if (prebuildComplete) {
    return;
  }

  runBunScript("prebuild");
  prebuildComplete = true;
}

function createForgeConfig(): ForgeConfig {
  const branding = loadBranding();
  const { appName, appPrefix, orgName, orgEmail } = branding;

  return {
    packagerConfig: {
      name: appName,
      executableName: appPrefix,
      icon: "./build/icon",
      appBundleId: `dev.${appPrefix}.app`,
      appCategoryType: "public.app-category.productivity",
      asar: true,
      protocols: [
        {
          name: `${appName} Auth`,
          schemes: [appPrefix],
        },
      ],
      ignore: [
        /^\/out($|\/)/,
        /^\/release($|\/)/,
        /^\/src($|\/)/,
        /^\/node_modules($|\/)/,
        /^\/scripts($|\/)/,
        /^\/README\.md$/,
        /^\/tsconfig\.json$/,
      ],
    },
    makers: [
      new MakerZIP({}, ["darwin"]),
      new MakerDMG(
        {
          name: `${appName}-mac`,
        },
        ["darwin"]
      ),
      new MakerSquirrel(
        {
          name: appPrefix,
          authors: orgName ?? appName,
          description: `${appName} desktop application`,
          setupExe: `${appName}-windows.exe`,
        },
        ["win32"]
      ),
      new MakerDeb(
        {
          options: {
            bin: appPrefix,
            maintainer:
              orgName && orgEmail
                ? `${orgName} <${orgEmail}>`
                : (orgName ?? orgEmail ?? appName),
            homepage: branding.appUrl,
            icon: "./build/icon.png",
            categories: ["Utility"],
          },
        },
        ["linux"]
      ),
      new MakerRpm(
        {
          options: {
            bin: appPrefix,
            homepage: branding.appUrl,
            icon: "./build/icon.png",
            license: "Apache-2.0",
          },
        },
        ["linux"]
      ),
    ],
    hooks: {
      generateAssets: async () => {
        ensurePrebuild();
      },
      preStart: async () => {
        runBunScript("build", { NODE_ENV: "development" });
      },
      prePackage: async () => {
        runBunScript("build", { NODE_ENV: "production" });
      },
    },
  };
}

const config = createForgeConfig();

export default config;
